<?php

/** Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
 * will be: 1,2,3,5,8,13,21,34,55,89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four milion, find the sum of the even-valued terms. 
 */

    function fib($n) {

         $a = 1;
         $b = 2;

         $s = Array();

         while($a < $n) { 

               $c = $a + $b;
               if($a%2 == 0) array_push($s,$a);
               $a = $b;
               $b = $c;
         } 

         $r = 0; 

         for($i = 0; $i < count($s); $i++) $r += intval($s[$i]);

       return $r; 
    }

    echo(fib(4000000));
?>